# Generated by Django 4.2 on 2024-07-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'void'), (10, 'paid'), (20, 'Error'), (30, 'User Canceled'), (31, 'Refunded')], db_index=True, default=0, verbose_name='status'),
        ),
    ]
