# Generated by Django 4.2 on 2024-07-19 16:40

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_package_is_enable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='update_time',
        ),
        migrations.AddField(
            model_name='package',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sku',
            field=models.CharField(db_index=True, max_length=20, validators=[utils.validators.SKUValidator()], verbose_name='stock keeping unit'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expire time'),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscriptions',
        ),
    ]
